### ISSUE TITLE
Add examples of projects using this GitHub Action.

### ISSUE THREAD

**Issue by shivammathur** [shivammathur/setup-php#46]
If you are using this GitHub Action in any particular PHP framework. Consider adding your workflow's `yml` as an example.

Add your `yml` file to the [examples](https://github.com/shivammathur/setup-php/tree/master/examples) directory and a link in the README [here](https://github.com/shivammathur/setup-php#examples)

Also see [contributor's guide](https://github.com/shivammathur/setup-php/blob/master/.github/CONTRIBUTING.md) before you submit your PR. 

- [x] Laravel - Added in #47 
- [x] Symfony - Added in #55 
- [x] CodeIgniter - Added in #55 
- [x] Slim Framework - Added in #49 
- [x] Yii PHP Framework - Added in #55 
- [x] Zend Framework - Added in #55
